---
title: "reproducible document"
author: "Melodie Schneider"
format: html
---

## Basics of R

```{r}
1 + 1
```

## Setup code chunk

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(
  here::here("data/post-meal-insulin.csv")
)
```
## About me

- Mélodie Jil Schneider
- University of Copenhagen

**I** do *basic research*

## Simple code

```{r}
3 * 3
```
## Showing the data

```{r}
post_meal_data
```
```{r}
glimpse(post_meal_data)
```


```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```
```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

@fig-bmi-histo

## Exercise: discrete plots

```{r}
#| fig-cap: "Distribution of groups"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete variables

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
## Putting tow plots side by side

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r side-by-side-figs}
#| label: fig-bmi-glycemi
#| fig-cap: "BMI and glycemia side by side"
#| fig-subcap:
#| - "Distribution of BMI"
#| - "Number of those with glycemia"
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

## Plotting two continous variables

```{r plotting two continous variables}
#| fig-cap: "Scatterplot of BMI and area under the curve of glycemia"
#| label: fig-scatterplot-bmi-aucglucose
#| echo: false
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()

```
